import Head from "next/head";
import Sidebar from "@/components/sidebar";
import { Inter } from "next/font/google";
import Dashboard from "@/components/dashboard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Buckz - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
      <Dashboard />
    </>
  );
}
